docs:
- README.md
- images/**
- vtasks/**.md

CI-CD:
- .github/**
- .pre-commit-config.yaml

j/backups:
- vtasks/jobs/backups/**

j/crypto:
- vtasks/jobs/crypto/**

j/dropbox:
- vtasks/jobs/dropbox/**

j/gcal:
- vtasks/jobs/gcal/**

j/gsheets:
- vtasks/jobs/gsheets/**

j/indexa:
- vtasks/jobs/indexa/**

j/local:
- vtasks/jobs/local/**

dbt:
- vtasks/vdbt/**

l/staging:
- vtasks/vdbt/models/staging/**

l/core:
- vtasks/vdbt/models/core/**

l/marts:
- vtasks/vdbt/models/marts/**

common:
- vtasks/common/**

schedules:
- vtasks/schedules/**

scripts:
- scripts/*
- scripts/**/*

deps:
- requirements.txt
- uv.lock
