vdbt:
  target: local

  outputs:
    local:
      type: duckdb
      path: "{{ env_var('PATH_DBT_DUCKDB') }}"
      schema: ""
      attach:
        - path: "{{ env_var('PATH_RAW_DUCKDB') }}"
          alias: villoro # This helps with motherduck compatibility
          read_only: true

    md:
      type: duckdb
      path: md:villoro
      schema: ""

    memory:
      type: duckdb
      path: ":memory:"
      schema: ""
