vdbt:
  target: local

  outputs:
    local:
      type: duckdb
      path: "{{ env_var('PATH_DBT_DUCKDB') }}"
      schema: ""
      attach:
        # This represents raw. Named villoro for Motherduck interoperability
        - path: "{{ env_var('PATH_VILLORO_DUCKDB') }}" 
          alias: raw
          read_only: true

    md:
      type: duckdb
      path: md:villoro
      schema: ""

    memory:
      type: duckdb
      path: ":memory:"
      schema: ""
