name: vdbt
version: '1.0.0'

profile: vdbt

analysis-paths: [analyses]
macro-paths: [macros]
model-paths: [models]
seed-paths: [seeds]
snapshot-paths: [snapshots]
test-paths: [tests]

clean-targets:
  - target
  - dbt_packages

vars:
  expensor:
    accounts:
      investments:
        - ing
        - degiro
        - crypto
        - indexa
        - indexa_pp
        - mintos
        - fastinvest
        - envestio
        - inbestme
        - glovo_ps
        - dh
      liquid:
        - caixa_enginers
        - caixa_enginers_diposit
        - ing_sin_nomina
        - ing_nomina
        - ing_naranja
        - ing_diposit
        - bunq
        - my_investor
        - revolut
        - n26
        - pibank
        - dukascopy
        - correos
        - monese
        - simplex
        - cash
        - norwegian_bank

seeds:
  +schema: internal

models:
  vdbt:
    +materialized: table

    staging:
      +tags: staging
      +materialized: ephemeral

      dropbox:
        +tags: dropbox
        +schema: stg__dropbox
        stg:
          +materialized: table

      gcal:
        +tags: gcal
        +schema: stg__gcal
        stg:
          +materialized: table

      gsheets:
        +tags: gsheets
        +schema: stg__gsheets
        stg:
          +materialized: table


    core:
      +tags: core
      +materialized: table

      expensor:
        +tags: expensor
        +schema: core__expensor

        int:
          +schema: internal

    marts:
      +tags: marts
      +materialized: table

      expensor:
        +tags: expensor
        +schema: marts__expensor

      gcal:
        +tags: gcal
        +schema: marts__gcal
