name: vdbt
version: '1.0.0'

profile: vdbt

analysis-paths: [analyses]
macro-paths: [macros]
model-paths: [models]
seed-paths: [seeds]
snapshot-paths: [snapshots]
test-paths: [tests]

clean-targets:
  - target
  - dbt_packages

vars:
  expensor:
    investments:
      accounts:
        - ing
        - degiro
        - crypto
        - indexa
        - indexa_pp
        - mintos
        - fastinvest
        - envestio
        - inbestme
        - glovo_ps
        - dh

seeds:
  +schema: internal

models:
  vdbt:
    +materialized: table

    staging:
      +materialized: ephemeral

      dropbox:
        +tags: dropbox
        +schema: stg__dropbox
        stg:
          +materialized: table

      gcal:
        +tags: gcal
        +schema: stg__gcal
        stg:
          +materialized: table

      gsheets:
        +tags: gsheets
        +schema: stg__gsheets
        stg:
          +materialized: table
