name: vdbt
version: '1.0.0'

profile: vdbt

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

clean-targets:
  - target
  - dbt_packages

seeds:
  +schema: internal

models:
  vdbt:
    +materialized: table

    staging:
      +materialized: ephemeral

      dropbox:
        +schema: stg__dropbox

        stg:
          +materialized: table
