name: Integration tests
env:
  VTASKS_TOKEN: ${{ secrets.VTASKS_TOKEN }}

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-dev

    - name: Tests
      run: |
        poetry run python src/master.py
